package models;
// Generated 4 oct. 2013 11:07:24 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Datatype generated by hbm2java
 */
public class Datatype  implements java.io.Serializable {


     private Integer idDt;
     private String intitule;
     private Set metadatas = new HashSet(0);

    public Datatype() {
    }

	
    public Datatype(String intitule) {
        this.intitule = intitule;
    }
    public Datatype(String intitule, Set metadatas) {
       this.intitule = intitule;
       this.metadatas = metadatas;
    }
   
    public Integer getIdDt() {
        return this.idDt;
    }
    
    public void setIdDt(Integer idDt) {
        this.idDt = idDt;
    }
    public String getIntitule() {
        return this.intitule;
    }
    
    public void setIntitule(String intitule) {
        this.intitule = intitule;
    }
    public Set getMetadatas() {
        return this.metadatas;
    }
    
    public void setMetadatas(Set metadatas) {
        this.metadatas = metadatas;
    }




}


