package models;
// Generated 4 oct. 2013 11:25:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.enterprise.context.SessionScoped;
import javax.inject.Named;

/**
 * Documents generated by hbm2java
 */
@Named(value = "documentsController")
@SessionScoped
public class DocumentsController  implements java.io.Serializable {
    private DocumentsDAO documentDao;
    private Documents document;
    private static List<Documents> documents = null;

    public DocumentsController() {
	documentDao = new DocumentsDAO();
        document = new Documents();
        ListeDesDocument();
    }

    public void ListeDesDocument() {
        if (documents == null) setDocuments(documentDao.getDocuments());
    }
    
    public void ajouteDocument() {
        document.setIdDoc(documentDao.ajouteDocument(document));
        documents.add(document);
        document = new Documents();
    }
    
    public List<Documents> getDocuments() {
        return documents;
    }
    public void setDocuments(List<Documents> documents) {
        this.documents = documents;
    }
    public Documents getDocument() {
        return document;
    }
    public void setDocument(Documents document) {
        this.document = document;
    }
}


