package models;
// Generated 4 oct. 2013 11:25:37 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Documents generated by hbm2java
 */
public class Documents  implements java.io.Serializable {


     private Integer idDoc;
     private String chemin;
     private String taille;
     private String formatDoc;
     private Set metadatas = new HashSet(0);
     private Set metadatas_1 = new HashSet(0);

    public Documents() {
    }

	
    public Documents(String taille, String formatDoc) {
        this.taille = taille;
        this.formatDoc = formatDoc;
    }
    public Documents(String chemin, String taille, String formatDoc, Set metadatas, Set metadatas_1) {
       this.chemin = chemin;
       this.taille = taille;
       this.formatDoc = formatDoc;
       this.metadatas = metadatas;
       this.metadatas_1 = metadatas_1;
    }
   
    public Integer getIdDoc() {
        return this.idDoc;
    }
    
    public void setIdDoc(Integer idDoc) {
        this.idDoc = idDoc;
    }
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }
    public String getTaille() {
        return this.taille;
    }
    
    public void setTaille(String taille) {
        this.taille = taille;
    }
    public String getFormatDoc() {
        return this.formatDoc;
    }
    
    public void setFormatDoc(String formatDoc) {
        this.formatDoc = formatDoc;
    }
    public Set getMetadatas() {
        return this.metadatas;
    }
    
    public void setMetadatas(Set metadatas) {
        this.metadatas = metadatas;
    }
    public Set getMetadatas_1() {
        return this.metadatas_1;
    }
    
    public void setMetadatas_1(Set metadatas_1) {
        this.metadatas_1 = metadatas_1;
    }




}


