package models;
// Generated 4 oct. 2013 11:07:24 by Hibernate Tools 3.2.1.GA



/**
 * Metadata generated by hbm2java
 */
public class Metadata  implements java.io.Serializable {


     private Integer idMd;
     private Documents documents;
     private Datatype datatype;
     private String valeur;

    public Metadata() {
    }

    public Metadata(Documents documents, Datatype datatype, String valeur) {
       this.documents = documents;
       this.datatype = datatype;
       this.valeur = valeur;
    }
   
    public Integer getIdMd() {
        return this.idMd;
    }
    
    public void setIdMd(Integer idMd) {
        this.idMd = idMd;
    }
    public Documents getDocuments() {
        return this.documents;
    }
    
    public void setDocuments(Documents documents) {
        this.documents = documents;
    }
    public Datatype getDatatype() {
        return this.datatype;
    }
    
    public void setDatatype(Datatype datatype) {
        this.datatype = datatype;
    }
    public String getValeur() {
        return this.valeur;
    }
    
    public void setValeur(String valeur) {
        this.valeur = valeur;
    }




}


